# action.yml
name: 'test'
description: 'action test'
inputs:
  who-to-greet:  # id of input
    description: 'testing'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'test output'
runs:
  using: 'docker'
  image: 'Dockerfile'

