name: Docker Image CI

on:  
  push:
  workflow_dispatch:
jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/keceli/test:latest
        docker run ghcr.io/keceli/test:latest
        docker push ghcr.io/keceli/test:latest

