name: Docker Image CI

on:  
  push:
  workflow_dispatch:
jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker build . --tag ghcr.io/keceli/${GITHUB_REF_NAME}
        docker run ghcr.io/keceli/${GITHUB_REF_NAME}
        docker push ghcr.io/keceli/${GITHUB_REF_NAME}
